# MoreMinecraftAPI by chrismin13
enable-debug: false

http:
 localhost: 
 port: 8125
 host: 
 numReadThread: 4
 numWriteThread: 4
 
resource-pack:
 force-on-join: true
 overwrite-files: true
 
bossbar:
 show: true
 vanilla-items: true
 custom-items: true